spring.application.name=PlataformaTransportes

# S3
aws.region=us-east-1
aws.s3.bucket-name=plataforma-transportes
aws.efs.path=/efs/guias

# DEBUG
logging.level.org.springframework.web.servlet.DispatcherServlet=DEBUG

# OAUTH2
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.microsoftonline.com/75354a34-dafb-4d09-ade6-2538ff5197d3/v2.0